version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shahajjo-app
    ports:
      - "8003:8000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    container_name: shahajjo-mongodb
    restart: always
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./docker/mongo-data:/data/db
      - ./seed-data:/docker-entrypoint-initdb.d # mount the seed-data folder
